CC= gcc
CCFLAGS= -Wall -g -Wextra -Ofast
CCSTD = -std=c99

ejemplo1: ejemplo1.c
	$(CC) $(CCFLAGS) $(CCSTD) $< -o exe1

ejemplo2: ejemplo2.c
	$(CC) $(CCFLAGS) $(CCSTD) $< -o exe2

ejemplo3: ejemplo3.c
	$(CC) $(CCFLAGS) $(CCSTD) $< -o exe3

ejemplo4: ejemplo4.c
	$(CC) $(CCFLAGS) $(CCSTD) $< -o exe4

ejemplo5: ejemplo5.c
	$(CC) $(CCFLAGS) $(CCSTD) $< -o exe5

ejemplo6: ejemplo6.c
	$(CC) $(CCFLAGS) $(CCSTD) $< -o exe6

ejemplo7: ejemplo7.c
	$(CC) $(CCFLAGS) $(CCSTD) $< -o exe7

ejemplo8: ejemplo8.c
	$(CC) $(CCFLAGS) $(CCSTD) $< -o exe8

ejemplo9: ejemplo9.c
	$(CC) $(CCFLAGS) $(CCSTD) $< -o exe9

ejemplo10: ejemplo10.c
	$(CC) $(CCFLAGS) $(CCSTD) $< -o exe10



.PHONY: all
all: ejemplo1 ejemplo2